Improve helmfile sync retry mechanism in kind-cluster.yml
The updated code in the `.github/workflows/kind-cluster.yml` file now includes a retry mechanism for the `helmfile sync` command. This helps to mitigate issues where the initial execution of the command fails, by attempting to run it twice more before exiting the script with an error.

diff --git a/.github/workflows/kind-cluster.yml b/.github/workflows/kind-cluster.yml
--- a/.github/workflows/kind-cluster.yml
+++ b/.github/workflows/kind-cluster.yml
@@ -37,4 +37,14 @@ jobs:
 
       - name: apply helmfile
         run: |
-          helmfile --file ./helm sync
+          command_retry=0
+          until [ $command_retry -ge 2 ]
+          do
+            helmfile --file ./helm sync && break
+            command_retry=$[$command_retry+1]
+            if [ $command_retry -eq 2 ]; then
+                echo "Command failed after 2 attempts"
+                exit 1
+            fi
+            sleep 1
+          done
